spring.application.name=demo
server.port=8080

# MongoDB configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=Travel_Booking

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# VNPay Sandbox Configuration
vnpay.tmn-code=${VNP_TMN_CODE}
vnpay.hash-secret=${VNP_HASH_SECRET}
vnpay.pay-url=${VNP_URL}
vnpay.return-url=http://localhost:8080/api/payment/vnpay-return
vnpay.version=2.1.0
vnpay.command=pay

# PayPal Configuration
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_SECRET}
paypal.mode=sandbox

# Frontend URL (for redirect after payment)
app.frontend.url=http://localhost:5173

# OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=public_profile